server:
  port: 9001

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  kafka:
    template:
      default-topic: order-events
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092

---
spring:
  profiles: prod
  kafka:
    template:
      default-topic: order-events
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
